services:
  db:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  rails:
    build:
      context: ./rails
    command: bash -c "bundle exec rails s -b 0.0.0.0 -p 3000"
    volumes:
      - ./rails:/myapp
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=password
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - RAILS_ENV=development
  next:
      build:
        dockerfile: ./next/Dockerfile
      tty: true
      stdin_open: true
      volumes:
        - ./next:/app
      ports:
        - "8000:3000"
volumes:
  mysql_data: