source "https://rubygems.org"
git_source(:github) {|repo| "https://github.com/#{repo}.git" }

ruby "3.3.0"

# railsの起動時間を短縮する（標準gem）
gem "bootsnap", require: false

# MySQLに接続する
gem "mysql2"

# pumaサーバーを使えるようにする（標準gem）
gem "puma", "~> 6.0"

gem "psych", "~> 5.1.0", require: false

# rails本体（標準gem）
gem "rails", "~> 7.2.1"

gem "rack-cors"

# タイムゾーン情報を提供する（標準gem）
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

# ユーザー認証を提供する
gem "devise"

# devise を日本語化する
gem "devise-i18n"

# ユーザーのトークン認証を提供する
gem "devise_token_auth", github: "lynndylanhurley/devise_token_auth", branch: "master"

group :development, :test do
  # pry コンソールを使えるようにする。
  gem "factory_bot_rails"
  gem "faker"
  gem "letter_opener_web"
  gem "pry-byebug"
  gem "pry-doc"
  gem "pry-rails"
  gem "rspec-rails"
  gem "rubocop-faker"
  gem "rubocop-rails"
  gem "rubocop-rspec"
  gem "shoulda-matchers"
end
